# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7e1473a4ac77bc05f81b9ad4965510790fd1c8b6924ea0bae3f53139b33c9d5f1580cc597fe43ade6865aaf19f3a2b604ba52b2165977d63fb0e272741b2d9d

test:
  secret_key_base: eafffd1408c9515fa3dc44330531053ed7c069281d56a782aab71795054b71100ed8fef803f3199c672ebd7bc7b55827712286c6853c33bfcf99705dc359c443

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
